## Deliverable 2. Create a Customer Travel Destinations Map.

In [8]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config_challenge import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [12]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv(r"C:\Users\mitch\Class\World_Weather_Analysis\Weather_Database\WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Souillac,MU,-20.5167,57.5167,68.38,88,40,6.91,scattered clouds
1,1,Saint-Philippe,RE,-21.3585,55.7679,65.79,84,26,9.91,light rain
2,2,Busselton,AU,-33.6500,115.3333,48.27,85,8,6.82,clear sky
3,3,Ushuaia,AR,-54.8000,-68.3000,31.66,74,20,1.14,few clouds
4,4,Berlevag,NO,70.8578,29.0864,62.40,88,100,4.61,light rain

In [13]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 85

In [14]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] > min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Souillac,MU,-20.5167,57.5167,68.38,88,40,6.91,scattered clouds
1,1,Saint-Philippe,RE,-21.3585,55.7679,65.79,84,26,9.91,light rain
4,4,Berlevag,NO,70.8578,29.0864,62.40,88,100,4.61,light rain
6,6,Ribeira Grande,PT,38.5167,-28.7000,75.00,82,35,6.33,scattered clouds
8,8,Lorengau,PG,-2.0226,147.2712,82.71,77,86,9.55,overcast clouds
11,11,Yellowknife,CA,62.4560,-114.3525,72.12,46,20,6.91,few clouds
14,14,Port Alfred,ZA,-33.5906,26.8910,65.39,45,14,5.01,few clouds
16,16,Heers,BE,50.7500,5.3000,63.61,79,75,5.75,broken clouds
17,17,Atuona,PF,-9.8000,-139.0333,77.29,76,10,16.93,clear sky
19,19,Borovskoy,KZ,53.8000,64.1500,63.79,88,100,11.65,light rain

In [16]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                437
City                   437
Country                436
Lat                    437
Lng                    437
Max Temp               437
Humidity               437
Cloudiness             437
Wind Speed             437
Current Description    437
dtype: int64

In [18]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df.isnull().sum()

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [19]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Souillac,MU,68.38,scattered clouds,-20.5167,57.5167,
1,Saint-Philippe,RE,65.79,light rain,-21.3585,55.7679,
4,Berlevag,NO,62.40,light rain,70.8578,29.0864,
6,Ribeira Grande,PT,75.00,scattered clouds,38.5167,-28.7000,
8,Lorengau,PG,82.71,overcast clouds,-2.0226,147.2712,
11,Yellowknife,CA,72.12,few clouds,62.4560,-114.3525,
14,Port Alfred,ZA,65.39,few clouds,-33.5906,26.8910,
16,Heers,BE,63.61,broken clouds,50.7500,5.3000,
17,Atuona,PF,77.29,clear sky,-9.8000,-139.0333,
19,Borovskoy,KZ,63.79,light rain,53.8000,64.1500,

In [21]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [24]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Souillac,MU,68.38,scattered clouds,-20.5167,57.5167,Shanti Maurice Resort & Spa
1,Saint-Philippe,RE,65.79,light rain,-21.3585,55.7679,Le four à pain
4,Berlevag,NO,62.40,light rain,70.8578,29.0864,Kvitbrakka
6,Ribeira Grande,PT,75.00,scattered clouds,38.5167,-28.7000,Quinta da Meia Eira
8,Lorengau,PG,82.71,overcast clouds,-2.0226,147.2712,Lorengau Harbourside Hotel

In [25]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [27]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<d1>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [29]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.75)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))